Coffee Machine Project
Maxim621/NIX_java_education_Parfonov_Maxim pull request #6
Opened 2021-11-19 01:50 UTC by Maxim621

Coffee Machine Project - Stage 1

Coffee Machine Project - Stage 2

Coffee Machine Project - Stage 3

Coffee Machine Project - Stage 4

Coffee Machine Project - Stage 5

Coffee Machine Project - Stage 6

2021-11-20 12:11 UTC, maxsomochkin requested changes

2021-11-20 12:11 UTC, maxsomochkin commented on src/nix/education/java/coffeemachine/ChoiceOfActions.java
> +                        availWater = availWater - 250;
Логику в кейсах в отдельные методы

2021-11-20 12:11 UTC, maxsomochkin commented on src/nix/education/java/coffeemachine/ChoiceOfActions.java
> +                System.out.println("Write how many ml of water you want to add:");
Если много логики под if - тоже в отдельный метод

2021-11-20 12:11 UTC, maxsomochkin commented on NIX_java_education_Parfonov_Maxim.iml
> +</module>
Не добавляй в гит все вспомогательные файлы!

2021-11-27 20:03 UTC, asrubel commented on .idea/.gitignore
> +# Default ignored files
У тебя куча лишних файлов в репозитории - они здесь нужны - только java-файлы

2021-12-10 14:28 UTC, merged